### PR TITLE
The definitions file (index.d.ts) was lacking message and title properties.

### PR DESCRIPTION
**Pull request by ibnYusrat**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by ibnYusrat** [comment]
Not mentioning title or message was causing empty spacer at title and message position, which was looking awkward. Now if title or message is omitted, it simply doesn't include those and makes it look tidy. I have posted the merge request.

**Comment by xlmnxp** [comment]
thank you

**Comment by ibnYusrat** [comment]
Please let me know when its updated in npm also. I have to add it to my project.json. 

جزاك الله خيرا يا صديقي العزيز

**Comment by xlmnxp** [comment]
@ibnYusrat now available in npm ```📦  nativescript-menu@1.1.2```

**Pull request merged**
